### ISSUE TITLE
RC1

### ISSUE THREAD

**Issue by BeRightBack** [jerriep/LocalizationByUser#1]
doesn't work on RC1

**Comment by jerriep** [comment]
Yes, because when I wrote the blog post RC1 was not out. It worked at the time on beta8. I have no intention of keeping my blog posts and the related samples updated to the latest versions.

**Comment by BeRightBack** [comment]
I'll try to find what's changed, as it's exactly what I need as a start for multilanguage website, and yes it worked perfectly on beta8, Tanks
